server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: cinema-service
          uri: lb://cinema-service
          predicates:
            - Path=/api/cinemas/**,/api/halls/**,/api/seats/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**,/api/screenings/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka-secret@discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true